apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: mynewacr887887.azurecr.io/acr-demo-app:task-build-1.0
        ports:
        - containerPort: 5000
        env:
        - name: APP_ENV
          value: "production"
